// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __AF_GEN_EVENT__
#define __AF_GEN_EVENT__


// Code used to configure the cluster event mechanism
#define EMBER_AF_GENERATED_EVENT_CODE \
  EmberEventControl emberAfTimeClusterServerTickCallbackControl1; \
  EmberEventControl emberAfTunnelingClusterClientTickCallbackControl1; \
  EmberEventControl emberAfTunnelingClusterServerTickCallbackControl1; \
  EmberEventControl emberAfSubGhzClusterServerTickCallbackControl1; \
  EmberEventControl emberAfKeyEstablishmentClusterServerTickCallbackControl1; \
  EmberEventControl emberAfTimeClusterServerTickCallbackControl2; \
  EmberEventControl emberAfKeyEstablishmentClusterServerTickCallbackControl2; \
  EmberEventControl emberAfTimeClusterServerTickCallbackControl3; \
  EmberEventControl emberAfKeyEstablishmentClusterServerTickCallbackControl3; \
  EmberEventControl emberAfTimeClusterServerTickCallbackControl4; \
  EmberEventControl emberAfKeyEstablishmentClusterServerTickCallbackControl4; \
  extern EmberEventControl emberAfPluginFormAndJoinCleanupEventControl; \
  extern EmberEventControl emberAfPluginKeyEstablishmentApsDuplicateDetectionEventControl; \
  extern EmberEventControl emberAfPluginNetworkFindTickEventControl; \
  extern EmberEventControl emberAfPluginScanDispatchScanEventControl; \
  extern EmberEventControl metroData; \
  extern void emberAfPluginFormAndJoinCleanupEventHandler(void); \
  extern void emberAfPluginKeyEstablishmentApsDuplicateDetectionEventHandler(void); \
  extern void emberAfPluginNetworkFindTickEventHandler(void); \
  extern void emberAfPluginScanDispatchScanEventHandler(void); \
  extern void metroHandler(void); \
  static void clusterTickWrapper(EmberEventControl *control, EmberAfTickFunction callback, uint8_t endpoint) \
  { \
    emberAfPushEndpointNetworkIndex(endpoint); \
    emberEventControlSetInactive(*control); \
    (*callback)(endpoint); \
    emberAfPopNetworkIndex(); \
  } \
  void emberAfTimeClusterServerTickCallbackWrapperFunction1(void) { clusterTickWrapper(&emberAfTimeClusterServerTickCallbackControl1, emberAfTimeClusterServerTickCallback, 1); } \
  void emberAfTunnelingClusterClientTickCallbackWrapperFunction1(void) { clusterTickWrapper(&emberAfTunnelingClusterClientTickCallbackControl1, emberAfTunnelingClusterClientTickCallback, 1); } \
  void emberAfTunnelingClusterServerTickCallbackWrapperFunction1(void) { clusterTickWrapper(&emberAfTunnelingClusterServerTickCallbackControl1, emberAfTunnelingClusterServerTickCallback, 1); } \
  void emberAfSubGhzClusterServerTickCallbackWrapperFunction1(void) { clusterTickWrapper(&emberAfSubGhzClusterServerTickCallbackControl1, emberAfSubGhzClusterServerTickCallback, 1); } \
  void emberAfKeyEstablishmentClusterServerTickCallbackWrapperFunction1(void) { clusterTickWrapper(&emberAfKeyEstablishmentClusterServerTickCallbackControl1, emberAfKeyEstablishmentClusterServerTickCallback, 1); } \
  void emberAfTimeClusterServerTickCallbackWrapperFunction2(void) { clusterTickWrapper(&emberAfTimeClusterServerTickCallbackControl2, emberAfTimeClusterServerTickCallback, 2); } \
  void emberAfKeyEstablishmentClusterServerTickCallbackWrapperFunction2(void) { clusterTickWrapper(&emberAfKeyEstablishmentClusterServerTickCallbackControl2, emberAfKeyEstablishmentClusterServerTickCallback, 2); } \
  void emberAfTimeClusterServerTickCallbackWrapperFunction3(void) { clusterTickWrapper(&emberAfTimeClusterServerTickCallbackControl3, emberAfTimeClusterServerTickCallback, 3); } \
  void emberAfKeyEstablishmentClusterServerTickCallbackWrapperFunction3(void) { clusterTickWrapper(&emberAfKeyEstablishmentClusterServerTickCallbackControl3, emberAfKeyEstablishmentClusterServerTickCallback, 3); } \
  void emberAfTimeClusterServerTickCallbackWrapperFunction4(void) { clusterTickWrapper(&emberAfTimeClusterServerTickCallbackControl4, emberAfTimeClusterServerTickCallback, 4); } \
  void emberAfKeyEstablishmentClusterServerTickCallbackWrapperFunction4(void) { clusterTickWrapper(&emberAfKeyEstablishmentClusterServerTickCallbackControl4, emberAfKeyEstablishmentClusterServerTickCallback, 4); } \


// EmberEventData structs used to populate the EmberEventData table
#define EMBER_AF_GENERATED_EVENTS   \
  { &emberAfTimeClusterServerTickCallbackControl1, emberAfTimeClusterServerTickCallbackWrapperFunction1 }, \
  { &emberAfTunnelingClusterClientTickCallbackControl1, emberAfTunnelingClusterClientTickCallbackWrapperFunction1 }, \
  { &emberAfTunnelingClusterServerTickCallbackControl1, emberAfTunnelingClusterServerTickCallbackWrapperFunction1 }, \
  { &emberAfSubGhzClusterServerTickCallbackControl1, emberAfSubGhzClusterServerTickCallbackWrapperFunction1 }, \
  { &emberAfKeyEstablishmentClusterServerTickCallbackControl1, emberAfKeyEstablishmentClusterServerTickCallbackWrapperFunction1 }, \
  { &emberAfTimeClusterServerTickCallbackControl2, emberAfTimeClusterServerTickCallbackWrapperFunction2 }, \
  { &emberAfKeyEstablishmentClusterServerTickCallbackControl2, emberAfKeyEstablishmentClusterServerTickCallbackWrapperFunction2 }, \
  { &emberAfTimeClusterServerTickCallbackControl3, emberAfTimeClusterServerTickCallbackWrapperFunction3 }, \
  { &emberAfKeyEstablishmentClusterServerTickCallbackControl3, emberAfKeyEstablishmentClusterServerTickCallbackWrapperFunction3 }, \
  { &emberAfTimeClusterServerTickCallbackControl4, emberAfTimeClusterServerTickCallbackWrapperFunction4 }, \
  { &emberAfKeyEstablishmentClusterServerTickCallbackControl4, emberAfKeyEstablishmentClusterServerTickCallbackWrapperFunction4 }, \
  { &emberAfPluginFormAndJoinCleanupEventControl, emberAfPluginFormAndJoinCleanupEventHandler }, \
  { &emberAfPluginKeyEstablishmentApsDuplicateDetectionEventControl, emberAfPluginKeyEstablishmentApsDuplicateDetectionEventHandler }, \
  { &emberAfPluginNetworkFindTickEventControl, emberAfPluginNetworkFindTickEventHandler }, \
  { &emberAfPluginScanDispatchScanEventControl, emberAfPluginScanDispatchScanEventHandler }, \
  { &metroData, metroHandler }, \


#define EMBER_AF_GENERATED_EVENT_STRINGS   \
  "Time Cluster Server EP 1",  \
  "Tunneling Cluster Client EP 1",  \
  "Tunneling Cluster Server EP 1",  \
  "Sub-GHz Cluster Server EP 1",  \
  "Key Establishment Cluster Server EP 1",  \
  "Time Cluster Server EP 2",  \
  "Key Establishment Cluster Server EP 2",  \
  "Time Cluster Server EP 3",  \
  "Key Establishment Cluster Server EP 3",  \
  "Time Cluster Server EP 4",  \
  "Key Establishment Cluster Server EP 4",  \
  "Form and Join Library Plugin Cleanup",  \
  "Key Establishment Plugin ApsDuplicateDetection",  \
  "Network Find Plugin Tick",  \
  "Scan Dispatch Plugin Scan",  \
  "Metro data",  \


// The length of the event context table used to track and retrieve cluster events
#define EMBER_AF_EVENT_CONTEXT_LENGTH 11

// EmberAfEventContext structs used to populate the EmberAfEventContext table
#define EMBER_AF_GENERATED_EVENT_CONTEXT { 0x1, 0xa, false, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfTimeClusterServerTickCallbackControl1}, \
{ 0x1, 0x704, true, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfTunnelingClusterClientTickCallbackControl1}, \
{ 0x1, 0x704, false, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfTunnelingClusterServerTickCallbackControl1}, \
{ 0x1, 0x70b, false, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfSubGhzClusterServerTickCallbackControl1}, \
{ 0x1, 0x800, false, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfKeyEstablishmentClusterServerTickCallbackControl1}, \
{ 0x2, 0xa, false, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfTimeClusterServerTickCallbackControl2}, \
{ 0x2, 0x800, false, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfKeyEstablishmentClusterServerTickCallbackControl2}, \
{ 0x3, 0xa, false, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfTimeClusterServerTickCallbackControl3}, \
{ 0x3, 0x800, false, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfKeyEstablishmentClusterServerTickCallbackControl3}, \
{ 0x4, 0xa, false, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfTimeClusterServerTickCallbackControl4}, \
{ 0x4, 0x800, false, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfKeyEstablishmentClusterServerTickCallbackControl4}


#endif // __AF_GEN_EVENT__
