// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// This file contains the mapping for the command line configuration

#include "app/framework/include/af.h"
#include "app/framework/cli/custom-cli.h"
#include EMBER_AF_API_COMMAND_INTERPRETER2

void emAfCliBsendCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const bsendCommandArguments[] = {
  "Source endpoint to send a binding based message from",
  NULL
};
#endif


void changeKeyCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const changekeyLinkCommandArguments[] = {
  "The link key provided as a 16 byte array",
  NULL
};
#endif


void changeKeyCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const changekeyNetworkCommandArguments[] = {
  "The network key provided as a 16 byte array",
  NULL
};
#endif


static EmberCommandEntry emberCommandChangekeyTable[] = {
  emberCommandEntryActionWithDetails("link", changeKeyCommand, "b", "Change the link key to the one provided in the 16 byte array argument  ...", changekeyLinkCommandArguments),
  emberCommandEntryActionWithDetails("network", changeKeyCommand, "b", "Change the network key to the 16 byte array provided as an argument to ...", changekeyNetworkCommandArguments),
  emberCommandEntryTerminator(),
};
void emberAfPrintAllOff(void);
void emberAfPrintAllOn(void);
void printOffCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const debugprintOffCommandArguments[] = {
  "The debug area mask listed in the <application>.h file",
  NULL
};
#endif


void printOnCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const debugprintOnCommandArguments[] = {
  "The debug area mask listed in the <application>.h file",
  NULL
};
#endif


void emberAfPrintStatus(void);
static EmberCommandEntry emberCommandDebugprintTable[] = {
  emberCommandEntryActionWithDetails("all_off", emberAfPrintAllOff, "", "Turns off all debug printing", NULL),
  emberCommandEntryActionWithDetails("all_on", emberAfPrintAllOn, "", "Turns on all compiled in debug printing", NULL),
  emberCommandEntryActionWithDetails("off", printOffCommand, "u", "Turns off compiled in debug printing for a specific debug printing are ...", debugprintOffCommandArguments),
  emberCommandEntryActionWithDetails("on", printOnCommand, "u", "Turns on compiled in debug printing for a specific debug printing area ...", debugprintOnCommandArguments),
  emberCommandEntryActionWithDetails("status", emberAfPrintStatus, "", "Prints out the current settings for debug printing on the device", NULL),
  emberCommandEntryTerminator(),
};
void echoCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const echoCommandArguments[] = {
  "bool indicating whether to turn echo on (1) or off (0)",
  NULL
};
#endif


void enableDisableEndpoint(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const endpointDisableCommandArguments[] = {
  "Endpoint in question.",
  NULL
};
#endif


void enableDisableEndpoint(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const endpointEnableCommandArguments[] = {
  "Endpoint in question.",
  NULL
};
#endif


void endpointPrint(void);
static EmberCommandEntry emberCommandEndpointTable[] = {
  emberCommandEntryActionWithDetails("disable", enableDisableEndpoint, "u", "Disable the endpoint for processing ZCL messages.", endpointDisableCommandArguments),
  emberCommandEntryActionWithDetails("enable", enableDisableEndpoint, "u", "Enable the endpoint for processing ZCL messages.", endpointEnableCommandArguments),
  emberCommandEntryActionWithDetails("print", endpointPrint, "", "Print the status of all the endpoints.", NULL),
  emberCommandEntryTerminator(),
};
void printEvents(void);
void helpCommand(void);
void emAfCliInfoCommand(void);
void interpanCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const interpanGroupCommandArguments[] = {
  "group id to send to",
  "destination pan id",
  "destination profile ID",
  NULL
};
#endif


void interpanLongCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const interpanLongCommandArguments[] = {
  "long ieee address to send the interpan message to",
  "two byte destination PA ID",
  "two byte destination profile ID",
  "two byte options",
  NULL
};
#endif


void interpanCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const interpanShortCommandArguments[] = {
  "group id to send to",
  "destination pan id",
  "destination profile ID",
  NULL
};
#endif


static EmberCommandEntry emberCommandInterpanTable[] = {
  emberCommandEntryActionWithDetails("group", interpanCommand, "vvv", "send an interpan message to a group id.", interpanGroupCommandArguments),
  emberCommandEntryActionWithDetails("long", interpanLongCommand, "bvvv", "Send an interpan message to a long address (8 byte eui64)", interpanLongCommandArguments),
  emberCommandEntryActionWithDetails("short", interpanCommand, "vvv", "Send an interpan message to a short id.", interpanShortCommandArguments),
  emberCommandEntryTerminator(),
};
void keysClearCommand(void);
void keysDeleteCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const keysDeleteCommandArguments[] = {
  "index into the security key table",
  NULL
};
#endif


void keysPrintCommand(void);
static EmberCommandEntry emberCommandKeysTable[] = {
  emberCommandEntryActionWithDetails("clear", keysClearCommand, "", "Clear all security keys", NULL),
  emberCommandEntryActionWithDetails("delete", keysDeleteCommand, "u", "Delete a security key from a given index", keysDeleteCommandArguments),
  emberCommandEntryActionWithDetails("print", keysPrintCommand, "", "Print all security keys out to the command line.", NULL),
  emberCommandEntryTerminator(),
};
void printAllLibraryStatus(void);
void networkPermitJoinCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const networkBroadPjoinCommandArguments[] = {
  "Number of seconds during which devices will be allowed to join the net ...",
  NULL
};
#endif


void networkChangeChannelCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const networkChangeChannelCommandArguments[] = {
  "The channel to change to.",
  NULL
};
#endif


void changeKeepAliveModeCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const networkChangeKeepAliveModeCommandArguments[] = {
  "The keep alive mode.",
  NULL
};
#endif


void networkExtendedPanIdCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const networkExtpanidCommandArguments[] = {
  "The bytes for the extended pan id",
  NULL
};
#endif


void findJoinableNetworkCommand(void);
void findMaskCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const networkFindMaskCommandArguments[] = {
  "channel page (0 and 28-31, if sub-GHz support is included)",
  "channel mask",
  NULL
};
#endif


void findModeCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const networkFindModeCommandArguments[] = {
  "Bit 0 = enable 2.4GHz, Bit 1 = enable sub-GHz",
  NULL
};
#endif


void findPrintCommand(void);
void findUnusedPanIdCommand(void);
static EmberCommandEntry emberCommandNetworkFindTable[] = {
  emberCommandEntryActionWithDetails("joinable", findJoinableNetworkCommand, "", "Begin a search for a joinable networ ...", NULL),
  emberCommandEntryActionWithDetails("mask", findMaskCommand, "uw", "Set a channel mask for a given channel page for 'find joinable' and 'f ...", networkFindMaskCommandArguments),
  emberCommandEntryActionWithDetails("mode", findModeCommand, "u", "Set a search mode for 'find joinable' and 'find unused'.", networkFindModeCommandArguments),
  emberCommandEntryActionWithDetails("print", findPrintCommand, "", "Print network search parameters (mode and channel masks).", NULL),
  emberCommandEntryActionWithDetails("unused", findUnusedPanIdCommand, "", "Begin a search for an unused Channel and Pan I ...", NULL),
  emberCommandEntryTerminator(),
};
void networkFormCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const networkFormCommandArguments[] = {
  "The channel on which to form the network",
  "One byte signed value indicating the TX power that the radio should be ...",
  "Two byte pan id for the network",
  NULL
};
#endif


void networkIdCommand(void);
void networkInitCommand(void);
void networkJoinCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const networkJoinCommandArguments[] = {
  "The channel on which to form the network",
  "One byte signed value indicating the TX power that the radio should be ...",
  "Two byte pan id for the network",
  NULL
};
#endif


void networkLeaveCommand(void);
void networkMultiPhyStartCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const networkMultiPhyStartCommandArguments[] = {
  "The page on which to form the network.",
  "The channel on which to form the network.",
  "One byte signed value indicating the TX power that the radio should be ...",
  "",
  NULL
};
#endif


void networkMultiPhyStopCommand(void);
void networkPermitJoinCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const networkPjoinCommandArguments[] = {
  "Number of seconds during which devices will be allowed to join the net ...",
  NULL
};
#endif


void networkRejoinCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const networkRejoinCommandArguments[] = {
  "Boolean indicating whether the device can rejoin secure or no ...",
  "4 byte channel mask which should be used to search for the network to  ...",
  NULL
};
#endif


void networkRejoinDiffDeviceTypeCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const networkRejoinDiffDeviceTypeCommandArguments[] = {
  "Boolean indicating whether the device can rejoin secure or no ...",
  "4 byte channel mask which should be used to search for the network to  ...",
  "An enumeration indicating the device type to rejoin a ...",
  NULL
};
#endif


void networkSetCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const networkSetCommandArguments[] = {
  "The network index to use for CLI commands",
  NULL
};
#endif


void networkChangeChildTimeoutOptionMaskCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const networkTimeoutOptionMaskCommandArguments[] = {
  "The timeout option mask.",
  NULL
};
#endif


static EmberCommandEntry emberCommandNetworkTable[] = {
  emberCommandEntryActionWithDetails("broad-pjoin", networkPermitJoinCommand, "u", "Permit joining on the network for a given number of seconds AND broadc ...", networkBroadPjoinCommandArguments),
  emberCommandEntryActionWithDetails("change-channel", networkChangeChannelCommand, "u", "Attempts to change device over to a different channel given in the cha ...", networkChangeChannelCommandArguments),
  emberCommandEntryActionWithDetails("change-keep-alive-mode", changeKeepAliveModeCommand, "u", "Switch between different keep alive modes supported by a router", networkChangeKeepAliveModeCommandArguments),
  emberCommandEntryActionWithDetails("extpanid", networkExtendedPanIdCommand, "b", "Write the extended pan id for the device.", networkExtpanidCommandArguments),
  emberCommandEntrySubMenu("find", emberCommandNetworkFindTable, ""),
  emberCommandEntryActionWithDetails("form", networkFormCommand, "usv", "Create a network on the given channel, power and panId.", networkFormCommandArguments),
  emberCommandEntryActionWithDetails("id", networkIdCommand, "", "Prints the current Node ID, EUI64, and Pan ID.", NULL),
  emberCommandEntryActionWithDetails("init", networkInitCommand, "", "Initialize a network; this is a test command used for tc-swap-out test ...", NULL),
  emberCommandEntryActionWithDetails("join", networkJoinCommand, "usv", "Join an existing network on the given channel, power and panId.", networkJoinCommandArguments),
  emberCommandEntryActionWithDetails("leave", networkLeaveCommand, "", "Leave the current network.", NULL),
  emberCommandEntryActionWithDetails("multi-phy-start", networkMultiPhyStartCommand, "uus*", "To start multi phy interface other than native and form the networ ...", networkMultiPhyStartCommandArguments),
  emberCommandEntryActionWithDetails("multi-phy-stop", networkMultiPhyStopCommand, "", "Terminates the multi phy interface", NULL),
  emberCommandEntryActionWithDetails("pjoin", networkPermitJoinCommand, "u", "Permit joining on the network for a given number of seconds", networkPjoinCommandArguments),
  emberCommandEntryActionWithDetails("rejoin", networkRejoinCommand, "uw", "Rejoin an existing network in a secure or insecure manner.", networkRejoinCommandArguments),
  emberCommandEntryActionWithDetails("rejoin-diff-device-type", networkRejoinDiffDeviceTypeCommand, "uwu", "Rejoin an existing network in a secure or insecure manner with a diffe ...", networkRejoinDiffDeviceTypeCommandArguments),
  emberCommandEntryActionWithDetails("set", networkSetCommand, "u", "Set the network index used by all future CLI command ...", networkSetCommandArguments),
  emberCommandEntryActionWithDetails("timeout-option-mask", networkChangeChildTimeoutOptionMaskCommand, "v", "Attempts to change child timeout option mask to filter out undesirable ...", networkTimeoutOptionMaskCommandArguments),
  emberCommandEntryTerminator(),
};
void optionApsRetryCommand(void);
void optionApsRetryCommand(void);
void optionApsRetryCommand(void);
static EmberCommandEntry emberCommandOptionApsretryTable[] = {
  emberCommandEntryActionWithDetails("default", optionApsRetryCommand, "", "Forces the AppFramework to set/clear the APS Retry option (in APS Fram ...", NULL),
  emberCommandEntryActionWithDetails("off", optionApsRetryCommand, "", "Forces the AppFramework to set/clear the APS Retry option (in APS Fram ...", NULL),
  emberCommandEntryActionWithDetails("on", optionApsRetryCommand, "", "Forces the AppFramework to set/clear the APS Retry option (in APS Fram ...", NULL),
  emberCommandEntryTerminator(),
};
void optionBindingTableClearCommand(void);
void optionBindingTablePrintCommand(void);
void optionBindingTableSetCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const optionBindingTableSetCommandArguments[] = {
  "one byte index into the binding table",
  "cluster id to send with the discovery message",
  "local endpoint to bind",
  "remote endpoint to bind",
  "8 byte IEEE address provided big endian",
  NULL
};
#endif


static EmberCommandEntry emberCommandOptionBindingTableTable[] = {
  emberCommandEntryActionWithDetails("clear", optionBindingTableClearCommand, "", "Clear the binding table", NULL),
  emberCommandEntryActionWithDetails("print", optionBindingTablePrintCommand, "", "Prints out the binding table to the command line.", NULL),
  emberCommandEntryActionWithDetails("set", optionBindingTableSetCommand, "uvuub", "Set a binding table entry for the arguments specified.", optionBindingTableSetCommandArguments),
  emberCommandEntryTerminator(),
};
void optionDiscoverCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const optionDiscCommandArguments[] = {
  "the profile id to send with the discovery message",
  "cluster id to send with the discovery message",
  NULL
};
#endif


void optionEndDeviceBindCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const optionEdbCommandArguments[] = {
  "The local endpoint whose simple descriptor will be used to create the  ...",
  NULL
};
#endif


void optionInstallCodeCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD) && !defined(EMBER_AF_HAS_SECURITY_PROFILE_NONE)
static const char * const optionInstallCodeCommandArguments[] = {
  "index into the link key table",
  "IEEE address to enter into the link key table",
  "install code including two-byte, little-endian CRC",
  NULL
};
#endif


void optionLinkCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const optionLinkCommandArguments[] = {
  "index into the link key table",
  "IEEE address to enter into the link key table",
  "link key to enter into the table",
  NULL
};
#endif


void optionPrintRxCommand(void);
void optionPrintRxCommand(void);
static EmberCommandEntry emberCommandOptionPrintRxMsgsTable[] = {
  emberCommandEntryActionWithDetails("disable", optionPrintRxCommand, "", "Disable the printing of received messages.", NULL),
  emberCommandEntryActionWithDetails("enable", optionPrintRxCommand, "", "Enable the printing of received messages.", NULL),
  emberCommandEntryTerminator(),
};
void optionRegisterCommand(void);
void optionApsSecurityCommand(void);
void optionApsSecurityCommand(void);
static EmberCommandEntry emberCommandOptionSecurityApsTable[] = {
  emberCommandEntryActionWithDetails("off", optionApsSecurityCommand, "", "Turns aps security off", NULL),
  emberCommandEntryActionWithDetails("on", optionApsSecurityCommand, "", "Turns aps security on", NULL),
  emberCommandEntryTerminator(),
};
void optionSecurityAllowTrustCenterRejoinUsingWellKnownKey(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const optionSecuritySetAllowTrustCenterRejoinUsingWellKnownKeyCommandArguments[] = {
  "Whether or not the Trust Center should allow trust center rejoins for  ...",
  NULL
};
#endif


void optionSecurityAllowTrustCenterRejoinUsingWellKnownKeyTimeout(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const optionSecuritySetAllowTrustCenterRejoinUsingWellKnownKeyTimeoutCommandArguments[] = {
  "The number of seconds that trust center rejoins will be responded to u ...",
  NULL
};
#endif


void optionSecuritySetKeyRequestPolicy(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const optionSecuritySetKeyRequestPolicyCommandArguments[] = {
  "The value to assign to emberTrustCenterLinkKeyRequestPolicy",
  "The value to assign to emberAppLinkKeyRequestPolicy",
  NULL
};
#endif


static EmberCommandEntry emberCommandOptionSecurityTable[] = {
  emberCommandEntrySubMenu("aps", emberCommandOptionSecurityApsTable, ""),
  emberCommandEntryActionWithDetails("set-allow-trust-center-rejoin-using-well-known-key", optionSecurityAllowTrustCenterRejoinUsingWellKnownKey, "u", "Set whether or not a Trust Center application will allow trust center  ...", optionSecuritySetAllowTrustCenterRejoinUsingWellKnownKeyCommandArguments),
  emberCommandEntryActionWithDetails("set-allow-trust-center-rejoin-using-well-known-key-timeout", optionSecurityAllowTrustCenterRejoinUsingWellKnownKeyTimeout, "v", "Sets the number of seconds to allow trust center rejoins for devices u ...", optionSecuritySetAllowTrustCenterRejoinUsingWellKnownKeyTimeoutCommandArguments),
  emberCommandEntryActionWithDetails("set-key-request-policy", optionSecuritySetKeyRequestPolicy, "uu", "Sets the local policy for handling TC link key requests and applicatio ...", optionSecuritySetKeyRequestPolicyCommandArguments),
  emberCommandEntryTerminator(),
};
static EmberCommandEntry emberCommandOptionTable[] = {
  emberCommandEntrySubMenu("apsretry", emberCommandOptionApsretryTable, ""),
  emberCommandEntrySubMenu("binding-table", emberCommandOptionBindingTableTable, ""),
  emberCommandEntryActionWithDetails("disc", optionDiscoverCommand, "vv", "Sends a ZDO Match Descriptor Request for the server side of the specif ...", optionDiscCommandArguments),
  emberCommandEntryActionWithDetails("edb", optionEndDeviceBindCommand, "u", "Sends a ZDO End Device Bind Request using the given local endpoint.", optionEdbCommandArguments),
#if !defined(EMBER_AF_HAS_SECURITY_PROFILE_NONE)
  emberCommandEntryActionWithDetails("install-code", optionInstallCodeCommand, "ubb", "Derives a link key from an install code, sets it in the transient key  ...", optionInstallCodeCommandArguments),
#endif //!defined(EMBER_AF_HAS_SECURITY_PROFILE_NONE)
  emberCommandEntryActionWithDetails("link", optionLinkCommand, "ubb", "Sets a link key in the link key tabl ...", optionLinkCommandArguments),
  emberCommandEntrySubMenu("print-rx-msgs", emberCommandOptionPrintRxMsgsTable, ""),
  emberCommandEntryActionWithDetails("register", optionRegisterCommand, "", "Initiates Smart Energy Registration including Key Establishmen ...", NULL),
  emberCommandEntrySubMenu("security", emberCommandOptionSecurityTable, ""),
  emberCommandEntryTerminator(),
};
void emberAfPluginAddressTableAddCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginAddressTableAddCommandArguments[] = {
  "Entry to be added.",
  NULL
};
#endif


void emberAfPluginAddressTableLookupCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginAddressTableLookupCommandArguments[] = {
  "Entry to be looked up.",
  NULL
};
#endif


void emberAfPluginAddressTablePrintCommand(void);
void emberAfPluginAddressTableRemoveCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginAddressTableRemoveCommandArguments[] = {
  "Entry to be removed.",
  NULL
};
#endif


void emberAfPluginAddressTableSetCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginAddressTableSetCommandArguments[] = {
  "index",
  "eui64",
  "node id",
  NULL
};
#endif


static EmberCommandEntry emberCommandPluginAddressTableTable[] = {
  emberCommandEntryActionWithDetails("add", emberAfPluginAddressTableAddCommand, "b", "Add an entry to the address table.", pluginAddressTableAddCommandArguments),
  emberCommandEntryActionWithDetails("lookup", emberAfPluginAddressTableLookupCommand, "b", "Lookup an entry in the address table.", pluginAddressTableLookupCommandArguments),
  emberCommandEntryActionWithDetails("print", emberAfPluginAddressTablePrintCommand, "", "Prints the address table.", NULL),
  emberCommandEntryActionWithDetails("remove", emberAfPluginAddressTableRemoveCommand, "b", "Remove an entry from the address table.", pluginAddressTableRemoveCommandArguments),
  emberCommandEntryActionWithDetails("set", emberAfPluginAddressTableSetCommand, "ubv", "Set an entry in the address table according to the arguments specified", pluginAddressTableSetCommandArguments),
  emberCommandEntryTerminator(),
};
void emberAfPluginConcentratorAggregationCommand(void);
void emberAfPluginConcentratorPrintSourceRouteTable(void);
void emberAfPluginConcentratorSetRouterBehaviorCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginConcentratorSetRouterBehaviorCommandArguments[] = {
  "The value of a EMBER_AF_PLUGIN_CONCENTRATOR_ROUTER_BEHAVIOR_ enum memb ...",
  NULL
};
#endif


void emberAfPluginConcentratorStartDiscovery(void);
void emberAfPluginConcentratorStatus(void);
void emberAfPluginConcentratorStopDiscovery(void);
static EmberCommandEntry emberCommandPluginConcentratorTable[] = {
  emberCommandEntryActionWithDetails("agg", emberAfPluginConcentratorAggregationCommand, "", "(Requires Concentrator Support to be enabled on this devic ...", NULL),
  emberCommandEntryActionWithDetails("print-table", emberAfPluginConcentratorPrintSourceRouteTable, "", "Print the SOC/NCP source route table.", NULL),
  emberCommandEntryActionWithDetails("set-router-behavior", emberAfPluginConcentratorSetRouterBehaviorCommand, "u", "This command allows the user to set the router behavior for this plugi ...", pluginConcentratorSetRouterBehaviorCommandArguments),
  emberCommandEntryActionWithDetails("start", emberAfPluginConcentratorStartDiscovery, "", "Starts the periodic broadcast of MTORRs", NULL),
  emberCommandEntryActionWithDetails("status", emberAfPluginConcentratorStatus, "", "Prints current status and configured parameters of the concentrator", NULL),
  emberCommandEntryActionWithDetails("stop", emberAfPluginConcentratorStopDiscovery, "", "Stops the periodic broadcast of MTORRs", NULL),
  emberCommandEntryTerminator(),
};
void emberAfPluginCounterPrintCounterTypeCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginCounterPrintCounterTypeCommandArguments[] = {
  "The counter type       to print.",
  NULL
};
#endif


static EmberCommandEntry emberCommandPluginCounterTable[] = {
  emberCommandEntryActionWithDetails("print-counter-type", emberAfPluginCounterPrintCounterTypeCommand, "u", "Print value of this particular counter.", pluginCounterPrintCounterTypeCommandArguments),
  emberCommandEntryTerminator(),
};
void emberAfPluginCountersClear(void);
void emberAfPluginCountersPrintCommand(void);
void emberAfPluginCountersPrintThresholdsCommand(void);
void emberAfPluginCountersResetThresholds(void);
void emberAfPluginCountersSendRequestCommand(void);
void emberAfPluginCountersSetThresholdCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginCountersSetThresholdCommandArguments[] = {
  "type of counter",
  "Threshold Value",
  NULL
};
#endif


void emberAfPluginCountersSimplePrintCommand(void);
static EmberCommandEntry emberCommandPluginCountersTable[] = {
  emberCommandEntryActionWithDetails("clear", emberAfPluginCountersClear, "", "Clear all counter values.", NULL),
  emberCommandEntryActionWithDetails("print", emberAfPluginCountersPrintCommand, "", "Print all counter values and clear them.", NULL),
  emberCommandEntryActionWithDetails("print-thresholds", emberAfPluginCountersPrintThresholdsCommand, "", "Prints the thresholds of all the counters.", NULL),
  emberCommandEntryActionWithDetails("reset-threshold", emberAfPluginCountersResetThresholds, "", "Resets all thresholds values to 0xFFFF.", NULL),
  emberCommandEntryActionWithDetails("send-request", emberAfPluginCountersSendRequestCommand, "", "Sends a request for ota counters", NULL),
  emberCommandEntryActionWithDetails("set-threshold", emberAfPluginCountersSetThresholdCommand, "uv", "Set a threshold value for a particular type of counter.", pluginCountersSetThresholdCommandArguments),
  emberCommandEntryActionWithDetails("simple-print", emberAfPluginCountersSimplePrintCommand, "", "Print all counter values.", NULL),
  emberCommandEntryTerminator(),
};
void emAfPluginFragmentationArtificialBlockDropCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD) && defined(EMBER_TEST)
static const char * const pluginFragmentationArtificialBlockDropCommandArguments[] = {
  "The block number to artificially drop to force a retr ...",
  NULL
};
#endif


void emAfPluginFragmentationSetWindowSizeCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD) && defined(EMBER_TEST)
static const char * const pluginFragmentationSetRxWindowSizeCommandArguments[] = {
  "The max number of the blocks received before an APS ack is generated.",
  NULL
};
#endif


static EmberCommandEntry emberCommandPluginFragmentationTable[] = {
#if defined(EMBER_TEST)
  emberCommandEntryActionWithDetails("artificial-block-drop", emAfPluginFragmentationArtificialBlockDropCommand, "u", "Artificially drops the block number defined by the passed argument onl ...", pluginFragmentationArtificialBlockDropCommandArguments),
#endif //defined(EMBER_TEST)
#if defined(EMBER_TEST)
  emberCommandEntryActionWithDetails("set-rx-window-size", emAfPluginFragmentationSetWindowSizeCommand, "u", "Sets the receive window siz ...", pluginFragmentationSetRxWindowSizeCommandArguments),
#endif //defined(EMBER_TEST)
  emberCommandEntryTerminator(),
};
void emAfKeyEstablishmentInterpanCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginKeyEstablishmentInterpanCommandArguments[] = {
  "The PAN ID that the target is located on.",
  "The target's EUI64 (big endian)",
  NULL
};
#endif


void emAfKeyEstablishmentStartCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginKeyEstablishmentStartCommandArguments[] = {
  "Target node ID.",
  "Target node's endpoint.",
  NULL
};
#endif


static EmberCommandEntry emberCommandPluginKeyEstablishmentTable[] = {
  emberCommandEntryActionWithDetails("interpan", emAfKeyEstablishmentInterpanCommand, "vb", "Initiate key establishment with the target device over interpan.", pluginKeyEstablishmentInterpanCommandArguments),
  emberCommandEntryActionWithDetails("start", emAfKeyEstablishmentStartCommand, "vu", "Initiates key establishment with the target node ID.", pluginKeyEstablishmentStartCommandArguments),
  emberCommandEntryTerminator(),
};
void emAfSubGhzServerCliChannelChangePrint(void);
void emAfSubGhzServerCliChannelChangeSet(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginSubGhzChannelChangeSetCommandArguments[] = {
  "Channel change attribute (bit mask)",
  NULL
};
#endif


static EmberCommandEntry emberCommandPluginSubGhzChannelChangeTable[] = {
  emberCommandEntryActionWithDetails("print", emAfSubGhzServerCliChannelChangePrint, "", "Print out the status of the sub-GHz channel change attribute.", NULL),
  emberCommandEntryActionWithDetails("set", emAfSubGhzServerCliChannelChangeSet, "w", "Set the status of the sub-GHz channel change attribute.", pluginSubGhzChannelChangeSetCommandArguments),
  emberCommandEntryTerminator(),
};
void emAfSubGhzServerCliChannelMaskPrint(void);
void emAfSubGhzServerCliChannelMaskSet(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginSubGhzChannelMaskSetCommandArguments[] = {
  "Channel 28 mask",
  "Channel 29 mask",
  "Channel 30 mask",
  "Channel 31 mask",
  NULL
};
#endif


static EmberCommandEntry emberCommandPluginSubGhzChannelMaskTable[] = {
  emberCommandEntryActionWithDetails("print", emAfSubGhzServerCliChannelMaskPrint, "", "Print out the status of all sub-GHz channel masks.", NULL),
  emberCommandEntryActionWithDetails("set", emAfSubGhzServerCliChannelMaskSet, "wwww", "Set one or more sub-GHz channel mask(s).", pluginSubGhzChannelMaskSetCommandArguments),
  emberCommandEntryTerminator(),
};
void emAfSubGhzServerCliClientStatus(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginSubGhzClientStatusCommandArguments[] = {
  "Client's Node ID of the given client",
  NULL
};
#endif


void emAfSubGhzServerCliDutyCycleLimitsPrint(void);
void emAfSubGhzServerCliDutyCycleLimitsSet(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginSubGhzLimitsSetCommandArguments[] = {
  "'Limited' Duty Cycle state threshold in % * 100 (i.e. 150 = 1.5%)",
  "'Critical' Duty Cycle state threshold in % * 100",
  "'Suspended' Duty Cycle state threshold in % * 100",
  NULL
};
#endif


static EmberCommandEntry emberCommandPluginSubGhzLimitsTable[] = {
  emberCommandEntryActionWithDetails("print", emAfSubGhzServerCliDutyCycleLimitsPrint, "", "Print the current Duty Cycle limits.", NULL),
  emberCommandEntryActionWithDetails("set", emAfSubGhzServerCliDutyCycleLimitsSet, "vvv", "Set the Duty Cycle limits.", pluginSubGhzLimitsSetCommandArguments),
  emberCommandEntryTerminator(),
};
void emAfSubGhzServerCliSuspendZclMessages(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginSubGhzSuspendZclMessagesCommandArguments[] = {
  "Node ID of the given client",
  "Endpoint of the given client",
  "Period in minutes",
  NULL
};
#endif


static EmberCommandEntry emberCommandPluginSubGhzTable[] = {
  emberCommandEntrySubMenu("channel-change", emberCommandPluginSubGhzChannelChangeTable, ""),
  emberCommandEntrySubMenu("channel-mask", emberCommandPluginSubGhzChannelMaskTable, ""),
  emberCommandEntryActionWithDetails("client-status", emAfSubGhzServerCliClientStatus, "v", "Print the given Sub-GHZ given client's current status.", pluginSubGhzClientStatusCommandArguments),
  emberCommandEntrySubMenu("limits", emberCommandPluginSubGhzLimitsTable, ""),
  emberCommandEntryActionWithDetails("suspend-zcl-messages", emAfSubGhzServerCliSuspendZclMessages, "vuu", "Send the SuspendZCLMessages command to the given client.", pluginSubGhzSuspendZclMessagesCommandArguments),
  emberCommandEntryTerminator(),
};
void importClearCommand(void);
void emAfTcExportCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD) && defined(EMBER_AF_PLUGIN_TRUST_CENTER_BACKUP_POSIX_FILE_BACKUP_SUPPORT)
static const char * const pluginTrustCenterBackupFileExportCommandArguments[] = {
  "path",
  NULL
};
#endif


void emAfTcImportCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD) && defined(EMBER_AF_PLUGIN_TRUST_CENTER_BACKUP_POSIX_FILE_BACKUP_SUPPORT)
static const char * const pluginTrustCenterBackupFileImportCommandArguments[] = {
  "path",
  NULL
};
#endif


void importKeyCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginTrustCenterBackupImportKeyCommandArguments[] = {
  "index",
  "partner e u i64",
  "new key",
  NULL
};
#endif


void printExportDataCommand(void);
void printImportDataCommand(void);
void restoreFromBackupCommand(void);
void setExtendedPanIdCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginTrustCenterBackupSetExtPanCommandArguments[] = {
  "extended pan id",
  NULL
};
#endif


static EmberCommandEntry emberCommandPluginTrustCenterBackupTable[] = {
  emberCommandEntryActionWithDetails("clear-import", importClearCommand, "", "Clear the import data set.", NULL),
#if defined(EMBER_AF_PLUGIN_TRUST_CENTER_BACKUP_POSIX_FILE_BACKUP_SUPPORT)
  emberCommandEntryActionWithDetails("file-export", emAfTcExportCommand, "b", "Write the TC backup data to a file.", pluginTrustCenterBackupFileExportCommandArguments),
#endif //defined(EMBER_AF_PLUGIN_TRUST_CENTER_BACKUP_POSIX_FILE_BACKUP_SUPPORT)
#if defined(EMBER_AF_PLUGIN_TRUST_CENTER_BACKUP_POSIX_FILE_BACKUP_SUPPORT)
  emberCommandEntryActionWithDetails("file-import", emAfTcImportCommand, "b", "Read the TC Backup data from a file and bring the TC back online.", pluginTrustCenterBackupFileImportCommandArguments),
#endif //defined(EMBER_AF_PLUGIN_TRUST_CENTER_BACKUP_POSIX_FILE_BACKUP_SUPPORT)
  emberCommandEntryActionWithDetails("import-key", importKeyCommand, "ubb", "Set a key in the import data set.", pluginTrustCenterBackupImportKeyCommandArguments),
  emberCommandEntryActionWithDetails("print-export", printExportDataCommand, "", "Print the set of export data that a TC must backup.", NULL),
  emberCommandEntryActionWithDetails("print-import", printImportDataCommand, "", "Print the import data set.", NULL),
  emberCommandEntryActionWithDetails("restore", restoreFromBackupCommand, "", "Use the import data set in a restore operation to bring the TC back on ...", NULL),
  emberCommandEntryActionWithDetails("set-ext-pan", setExtendedPanIdCommand, "b", "Set the extended PAN ID in the import data set.", pluginTrustCenterBackupSetExtPanCommandArguments),
  emberCommandEntryTerminator(),
};
void emAfPluginTunnelingClientCliClose(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginTunnelingClientCloseCommandArguments[] = {
  "The index of the tunnel to close.",
  NULL
};
#endif


void emAfPluginTunnelingClientCliPrint(void);
void emAfPluginTunnelingClientCliRequest(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginTunnelingClientRequestCommandArguments[] = {
  "The network address of the server to which the request will be sent.",
  "The local endpoint from which the request will be sent.",
  "The remote endpoint to which the request will be sent.",
  "The protocol id of the requested tunnel.",
  "The manufacturer code of the requested tunnel.",
  "1 if flow control support is requested or 0 if not.",
  NULL
};
#endif


void emAfPluginTunnelingClientCliTransfer(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginTunnelingClientTransferCommandArguments[] = {
  "The index of the tunnel through which to send the data.",
  "The data to send through the tunnel.",
  NULL
};
#endif


static EmberCommandEntry emberCommandPluginTunnelingClientTable[] = {
  emberCommandEntryActionWithDetails("close", emAfPluginTunnelingClientCliClose, "u", "Close a Tunneling cluster tunnel.", pluginTunnelingClientCloseCommandArguments),
  emberCommandEntryActionWithDetails("print", emAfPluginTunnelingClientCliPrint, "", "Print out the status of active tunnels.", NULL),
  emberCommandEntryActionWithDetails("request", emAfPluginTunnelingClientCliRequest, "vuuuvu", "Request a Tunneling cluster tunnel with a server.", pluginTunnelingClientRequestCommandArguments),
  emberCommandEntryActionWithDetails("transfer", emAfPluginTunnelingClientCliTransfer, "ub", "Transfer data to a server through a Tunneling cluster tunnel.", pluginTunnelingClientTransferCommandArguments),
  emberCommandEntryTerminator(),
};
void emberAfPluginTunnelingServerToggleBusyCommand(void);
void emAfPluginTunnelingServerCliPrint(void);
void emAfPluginTunnelingServerCliTransfer(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginTunnelingServerTransferCommandArguments[] = {
  "The identifier of the tunnel through which to send the data.",
  "The data to send through the tunnel.",
  NULL
};
#endif


static EmberCommandEntry emberCommandPluginTunnelingServerTable[] = {
  emberCommandEntryActionWithDetails("busy", emberAfPluginTunnelingServerToggleBusyCommand, "", "This command can be used as a test harness for testing a client's hand ...", NULL),
  emberCommandEntryActionWithDetails("print", emAfPluginTunnelingServerCliPrint, "", "Print out the status of active tunnels.", NULL),
  emberCommandEntryActionWithDetails("transfer", emAfPluginTunnelingServerCliTransfer, "vb", "Transfer data to a client through a Tunneling cluster tunnel.", pluginTunnelingServerTransferCommandArguments),
  emberCommandEntryTerminator(),
};
static EmberCommandEntry emberCommandPluginTable[] = {
  emberCommandEntrySubMenu("address-table", emberCommandPluginAddressTableTable, ""),
  emberCommandEntrySubMenu("concentrator", emberCommandPluginConcentratorTable, ""),
  emberCommandEntrySubMenu("counter", emberCommandPluginCounterTable, ""),
  emberCommandEntrySubMenu("counters", emberCommandPluginCountersTable, ""),
  emberCommandEntrySubMenu("fragmentation", emberCommandPluginFragmentationTable, ""),
  emberCommandEntrySubMenu("key-establishment", emberCommandPluginKeyEstablishmentTable, ""),
  emberCommandEntrySubMenu("sub-ghz", emberCommandPluginSubGhzTable, ""),
  emberCommandEntrySubMenu("trust-center-backup", emberCommandPluginTrustCenterBackupTable, ""),
  emberCommandEntrySubMenu("tunneling-client", emberCommandPluginTunnelingClientTable, ""),
  emberCommandEntrySubMenu("tunneling-server", emberCommandPluginTunnelingServerTable, ""),
  emberCommandEntryTerminator(),
};
void emberAfPrintAttributeTable(void);
void emberAfPrintEntropySource(void);
static EmberCommandEntry emberCommandPrintEntropyTable[] = {
  emberCommandEntryActionWithDetails("source", emberAfPrintEntropySource, "", "Print the the entropy source that is used for true random number gener ...", NULL),
  emberCommandEntryTerminator(),
};
void printTimeCommand(void);
static EmberCommandEntry emberCommandPrintTable[] = {
  emberCommandEntryActionWithDetails("attr", emberAfPrintAttributeTable, "", "Print the attribute table.", NULL),
  emberCommandEntrySubMenu("entropy", emberCommandPrintEntropyTable, ""),
  emberCommandEntryActionWithDetails("time", printTimeCommand, "", "Print out the time information", NULL),
  emberCommandEntryTerminator(),
};
void emAfCliRawCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const rawCommandArguments[] = {
  "two byte cluster id",
  "ZCL message, including ZCL header and payload",
  NULL
};
#endif


void emAfCliReadCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const readCommandArguments[] = {
  "endpoint of the attribute to read",
  "cluster id of the attribute to read",
  "attribute id of the attribute to read",
  "direction mask of the attribute to read (client=0 or server=1)",
  NULL
};
#endif


void resetCommand(void);
void getSetMfgToken(void);
void getSetMfgToken(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD) && !defined(EMBER_AF_HAS_SECURITY_PROFILE_NONE)
static const char * const securityMfgTokenSetCommandArguments[] = {
  "magic number",
  "value",
  NULL
};
#endif


static EmberCommandEntry emberCommandSecurityMfgTokenTable[] = {
#if !defined(EMBER_AF_HAS_SECURITY_PROFILE_NONE)
  emberCommandEntryActionWithDetails("get", getSetMfgToken, "", "", NULL),
#endif //!defined(EMBER_AF_HAS_SECURITY_PROFILE_NONE)
#if !defined(EMBER_AF_HAS_SECURITY_PROFILE_NONE)
  emberCommandEntryActionWithDetails("set", getSetMfgToken, "wv", "", securityMfgTokenSetCommandArguments),
#endif //!defined(EMBER_AF_HAS_SECURITY_PROFILE_NONE)
  emberCommandEntryTerminator(),
};
static EmberCommandEntry emberCommandSecurityTable[] = {
  emberCommandEntrySubMenu("mfg-token", emberCommandSecurityMfgTokenTable, ""),
  emberCommandEntryTerminator(),
};
void emAfCliSendCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const sendCommandArguments[] = {
  "short id of the device to send the message to",
  "The endpoint to send the message from",
  "The endpoint to send the message to",
  NULL
};
#endif


void emAfCliSendUsingMulticastBindingCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const sendUsingMulticastBindingCommandArguments[] = {
  "Whether to send via a multicast binding",
  NULL
};
#endif


void emAfCliSendCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const sendMulticastCommandArguments[] = {
  "group id of the multicast group to send the message to",
  "The endpoint to send the message from",
  NULL
};
#endif


void emAfCliTimesyncCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const timesyncCommandArguments[] = {
  "two byte short id of the time server",
  "source endpoint to send time sync from",
  "destination endpoint to expect response on",
  NULL
};
#endif


void emAfCliVersionCommand(void);
void emAfCliWriteCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const writeCommandArguments[] = {
  "endpoint of the attribute to write",
  "cluster id of the attribute to write",
  "attribute id of the attribute to write",
  "direction mask of the attribute to write (client=0 or server=1)",
  "the attribute type as listed in the generated file attribute-type.h",
  "string of bytes you wish to write into the attribute table.",
  NULL
};
#endif


static void zclBasicGlsrCommand(void) {
  zclSimpleServerCommand( ZCL_BASIC_CLUSTER_ID,
                          ZCL_GET_LOCALES_SUPPORTED_RESPONSE_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclBasicGlsrCommandArguments[] = {
  "discovery complete",
  "locale supported",
  "",
  NULL
};
#endif


static EmberCommandEntry emberCommandZclBasicTable[] = {
  emberCommandEntryActionWithDetails("glsr", zclBasicGlsrCommand, "ub*", "The locales supported response command is sent in response to a get lo ...", zclBasicGlsrCommandArguments),
  emberCommandEntryTerminator(),
};
static void zclDmGetEventConfigCommand(void) {
  zclSimpleServerCommand( ZCL_DEVICE_MANAGEMENT_CLUSTER_ID,
                          ZCL_GET_EVENT_CONFIGURATION_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclDmGetEventConfigCommandArguments[] = {
  "event id",
  NULL
};
#endif


static void zclDmPubChgOfSupplierCommand(void) {
  zclSimpleServerCommand( ZCL_DEVICE_MANAGEMENT_CLUSTER_ID,
                          ZCL_PUBLISH_CHANGE_OF_SUPPLIER_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclDmPubChgOfSupplierCommandArguments[] = {
  "current provider id",
  "issuer event id",
  "tariff type",
  "proposed provider id",
  "provider change implementation time",
  "provider change control",
  "proposed provider name",
  "proposed provider contact details",
  NULL
};
#endif


static void zclDmReqNewPassRespCommand(void) {
  zclSimpleServerCommand( ZCL_DEVICE_MANAGEMENT_CLUSTER_ID,
                          ZCL_REQUEST_NEW_PASSWORD_RESPONSE_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclDmReqNewPassRespCommandArguments[] = {
  "issuer event id",
  "implementation date time",
  "duration in minutes",
  "password type",
  "password",
  NULL
};
#endif


static void zclDmSetEventConfigCommand(void) {
  zclSimpleServerCommand( ZCL_DEVICE_MANAGEMENT_CLUSTER_ID,
                          ZCL_SET_EVENT_CONFIGURATION_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclDmSetEventConfigCommandArguments[] = {
  "issuer event id",
  "start date time",
  "event configuration",
  "configuration control",
  "event configuration payload",
  "",
  NULL
};
#endif


static EmberCommandEntry emberCommandZclDmTable[] = {
  emberCommandEntryActionWithDetails("get-event-config", zclDmGetEventConfigCommand, "v", "This command allows the server to request details of event configurati ...", zclDmGetEventConfigCommandArguments),
  emberCommandEntryActionWithDetails("pub-chg-of-supplier", zclDmPubChgOfSupplierCommand, "wwuwwwbb", "This command is used to change the Supplier (energy supplier) that is  ...", zclDmPubChgOfSupplierCommandArguments),
  emberCommandEntryActionWithDetails("req-new-pass-resp", zclDmReqNewPassRespCommand, "wwvub", "This command is used to send the current password to the client.", zclDmReqNewPassRespCommandArguments),
  emberCommandEntryActionWithDetails("set-event-config", zclDmSetEventConfigCommand, "wwuuu*", "This command provides a method to set the event configuration attribut ...", zclDmSetEventConfigCommandArguments),
  emberCommandEntryTerminator(),
};
static void zclDrlcCaCommand(void) {
  zclSimpleServerCommand( ZCL_DEMAND_RESPONSE_LOAD_CONTROL_CLUSTER_ID,
                          ZCL_CANCEL_ALL_LOAD_CONTROL_EVENTS_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclDrlcCaCommandArguments[] = {
  "cancel control",
  NULL
};
#endif


static void zclDrlcClCommand(void) {
  zclSimpleServerCommand( ZCL_DEMAND_RESPONSE_LOAD_CONTROL_CLUSTER_ID,
                          ZCL_CANCEL_LOAD_CONTROL_EVENT_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclDrlcClCommandArguments[] = {
  "issuer event id",
  "device class",
  "utility enrollment group",
  "cancel control",
  "effective time",
  NULL
};
#endif


void zclDrlcLoadControlEventCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclDrlcLceCommandArguments[] = {
  "4 byte event id for the load control event",
  "UEG of the load control event",
  "Start time for the load control event",
  "Duration for the load control event",
  "Control byte for the load control event",
  NULL
};
#endif


static EmberCommandEntry emberCommandZclDrlcTable[] = {
  emberCommandEntryActionWithDetails("ca", zclDrlcCaCommand, "u", "Command description for CancelAllLoadControlEvents", zclDrlcCaCommandArguments),
  emberCommandEntryActionWithDetails("cl", zclDrlcClCommand, "wvuuw", "Command description for CancelLoadControlEvent", zclDrlcClCommandArguments),
  emberCommandEntryActionWithDetails("lce", zclDrlcLoadControlEventCommand, "wuwvu", "Populate a buffer to send a static load control event with the followi ...", zclDrlcLceCommandArguments),
  emberCommandEntryTerminator(),
};
void zclGlobalDirectionCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclGlobalDirectionCommandArguments[] = {
  "The direction for global commands, 0 = client to server, 1 = server to ...",
  NULL
};
#endif


void zclGlobalCommandDiscoveryCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclGlobalDiscComGenCommandArguments[] = {
  "The cluster to find commands on.",
  "The command id to start the command search on.",
  "Max command ids to search for.",
  NULL
};
#endif


void zclGlobalCommandDiscoveryCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclGlobalDiscComRecCommandArguments[] = {
  "The cluster to find commands on.",
  "The command id to start the command search on.",
  "Max command ids to search for.",
  NULL
};
#endif


void zclGlobalDiscoverCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclGlobalDiscoverCommandArguments[] = {
  "The cluster id of the cluster to discover.",
  "The attribute id of the attribute to read during discovery.",
  "Max number of discovery responses.",
  NULL
};
#endif


void zclGlobalExpectReportFromMeCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclGlobalExpectReportFromMeCommandArguments[] = {
  "The cluster id for the requested report.",
  "The attribute id for the requested report.",
  "Maximum amount of time between reports.",
  NULL
};
#endif


void zclGlobalWriteCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclGlobalNwriteCommandArguments[] = {
  "The cluster id of the cluster to read from.",
  "The attribute id of the attribute to read.",
  "The type of the attribute to write.",
  "The data to be written.",
  NULL
};
#endif


void zclGlobalReadCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclGlobalReadCommandArguments[] = {
  "The cluster id of the cluster to read from.",
  "The attribute id of the attribute to read.",
  NULL
};
#endif


void zclGlobalReportCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclGlobalReportCommandArguments[] = {
  "The desired endpoint.",
  "The cluster id.",
  "The attribute id.",
  "The mask.",
  NULL
};
#endif


void zclGlobalReportReadCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclGlobalReportReadCommandArguments[] = {
  "The cluster id to read from.",
  "The attribute id to read from.",
  "0 for client-to-server, 1 for server-to-client.",
  NULL
};
#endif


void zclGlobalSendMeAReportCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclGlobalSendMeAReportCommandArguments[] = {
  "The cluster id of the requested report.",
  "The attribute id for requested report.",
  "The two byte ZigBee type value for the requested report.",
  "Minimum number of seconds between reports.",
  "Maximum number of seconds between reports.",
  "Amount of change to trigger a report.",
  NULL
};
#endif


void zclGlobalWriteCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclGlobalUwriteCommandArguments[] = {
  "The cluster id of the cluster to write to.",
  "The attribute id of the attribute to write.",
  "The type of the attribute to write.",
  "The data to be written.",
  NULL
};
#endif


void zclGlobalWriteCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclGlobalWriteCommandArguments[] = {
  "The cluster id of the cluster to write to.",
  "The attribute id of the attribute to write.",
  "The type of the attribute to write.",
  "The data to be written.",
  NULL
};
#endif


static EmberCommandEntry emberCommandZclGlobalTable[] = {
  emberCommandEntryActionWithDetails("direction", zclGlobalDirectionCommand, "u", "Sets the direction for global commands, either client to server or ser ...", zclGlobalDirectionCommandArguments),
  emberCommandEntryActionWithDetails("disc-com-gen", zclGlobalCommandDiscoveryCommand, "vuu", "Create a Discover Commands Generated command with associated values.", zclGlobalDiscComGenCommandArguments),
  emberCommandEntryActionWithDetails("disc-com-rec", zclGlobalCommandDiscoveryCommand, "vuu", "Create a Discover Commands Received command with associated values.", zclGlobalDiscComRecCommandArguments),
  emberCommandEntryActionWithDetails("discover", zclGlobalDiscoverCommand, "vvu", "Creates discovery message for devices with the associated cluster and  ...", zclGlobalDiscoverCommandArguments),
  emberCommandEntryActionWithDetails("expect-report-from-me", zclGlobalExpectReportFromMeCommand, "vvv", "Create a expect-report-from-me message with associated values.", zclGlobalExpectReportFromMeCommandArguments),
  emberCommandEntryActionWithDetails("nwrite", zclGlobalWriteCommand, "vvub", "Creates a global write command message to write to the cluster and att ...", zclGlobalNwriteCommandArguments),
  emberCommandEntryActionWithDetails("read", zclGlobalReadCommand, "vv", "Creates a global read command message to read from the cluster and att ...", zclGlobalReadCommandArguments),
  emberCommandEntryActionWithDetails("report", zclGlobalReportCommand, "uvvu", "", zclGlobalReportCommandArguments),
  emberCommandEntryActionWithDetails("report-read", zclGlobalReportReadCommand, "vvu", "Creates a global read reporting command for the associated cluster, at ...", zclGlobalReportReadCommandArguments),
  emberCommandEntryActionWithDetails("send-me-a-report", zclGlobalSendMeAReportCommand, "vvuvvb", "Creates a global send me a report command for the associated values.", zclGlobalSendMeAReportCommandArguments),
  emberCommandEntryActionWithDetails("uwrite", zclGlobalWriteCommand, "vvub", "Creates a global write undivided command message to write to the clust ...", zclGlobalUwriteCommandArguments),
  emberCommandEntryActionWithDetails("write", zclGlobalWriteCommand, "vvwb", "Creates a global write command message to write to the cluster and att ...", zclGlobalWriteCommandArguments),
  emberCommandEntryTerminator(),
};
static void zclMeteringCfgMirrorCommand(void) {
  zclSimpleServerCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_CONFIGURE_MIRROR_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMeteringCfgMirrorCommandArguments[] = {
  "issuer event id",
  "reporting interval",
  "mirror notification reporting",
  "notification scheme",
  NULL
};
#endif


static void zclMeteringCfgNftFlagsCommand(void) {
  zclSimpleServerCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_CONFIGURE_NOTIFICATION_FLAGS_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMeteringCfgNftFlagsCommandArguments[] = {
  "issuer event id",
  "notification scheme",
  "notification flag attribute id",
  "cluster id",
  "manufacturer code",
  "number of commands",
  "command ids",
  "",
  NULL
};
#endif


static void zclMeteringCfgNftSchemeCommand(void) {
  zclSimpleServerCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_CONFIGURE_NOTIFICATION_SCHEME_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMeteringCfgNftSchemeCommandArguments[] = {
  "issuer event id",
  "notification scheme",
  "notification flag order",
  NULL
};
#endif


static void zclMeteringGetNtfyMsgCommand(void) {
  zclSimpleServerCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_GET_NOTIFIED_MESSAGE_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMeteringGetNtfyMsgCommandArguments[] = {
  "notification scheme",
  "notification flag attribute id",
  "notification flags n",
  NULL
};
#endif


static void zclMeteringPubSsCommand(void) {
  zclSimpleServerCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_PUBLISH_SNAPSHOT_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMeteringPubSsCommandArguments[] = {
  "snapshot id",
  "snapshot time",
  "total snapshots found",
  "command index",
  "total commands",
  "snapshot cause",
  "snapshot payload type",
  "snapshot payload",
  "",
  NULL
};
#endif


static void zclMeteringRemoveMirrorCommand(void) {
  zclSimpleServerCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_REMOVE_MIRROR_COMMAND_ID);
}

static void zclMeteringRequestMirrorCommand(void) {
  zclSimpleServerCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_REQUEST_MIRROR_COMMAND_ID);
}

static void zclMeteringSchSnapshotRespCommand(void) {
  zclSimpleServerCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_SCHEDULE_SNAPSHOT_RESPONSE_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMeteringSchSnapshotRespCommandArguments[] = {
  "issuer event id",
  "snapshot response payload",
  "",
  NULL
};
#endif


static void zclMeteringStartSampRspCommand(void) {
  zclSimpleServerCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_START_SAMPLING_RESPONSE_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMeteringStartSampRspCommandArguments[] = {
  "sample id",
  NULL
};
#endif


static void zclMeteringSupStatRspCommand(void) {
  zclSimpleServerCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_SUPPLY_STATUS_RESPONSE_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMeteringSupStatRspCommandArguments[] = {
  "provider id",
  "issuer event id",
  "implementation date time",
  "supply status",
  NULL
};
#endif


static void zclMeteringTakeSnapshotRespCommand(void) {
  zclSimpleServerCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_TAKE_SNAPSHOT_RESPONSE_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMeteringTakeSnapshotRespCommandArguments[] = {
  "snapshot id",
  "snapshot confirmation",
  NULL
};
#endif


static EmberCommandEntry emberCommandZclMeteringTable[] = {
  emberCommandEntryActionWithDetails("cfg-mirror", zclMeteringCfgMirrorCommand, "w0uu", "ConfigureMirror is sent to the mirror once the mirror has been created ...", zclMeteringCfgMirrorCommandArguments),
  emberCommandEntryActionWithDetails("cfg-nft-flags", zclMeteringCfgNftFlagsCommand, "wuvvvuu*", "The ConfigureNotificationFlags command is used to set the commands rel ...", zclMeteringCfgNftFlagsCommandArguments),
  emberCommandEntryActionWithDetails("cfg-nft-scheme", zclMeteringCfgNftSchemeCommand, "wuw", "The ConfigureNotificationScheme is sent to the mirror once the mirror  ...", zclMeteringCfgNftSchemeCommandArguments),
  emberCommandEntryActionWithDetails("get-ntfy-msg", zclMeteringGetNtfyMsgCommand, "uvw", "The GetNotifiedMessage command is used only when a BOMD is being mirro ...", zclMeteringGetNtfyMsgCommandArguments),
  emberCommandEntryActionWithDetails("pub-ss", zclMeteringPubSsCommand, "wwuuuwuu*", "This command is generated in response to a GetSnapshot comman ...", zclMeteringPubSsCommandArguments),
  emberCommandEntryActionWithDetails("remove-mirror", zclMeteringRemoveMirrorCommand, "", "This command is used to request the ESI to remove its mirror of Meteri ...", NULL),
  emberCommandEntryActionWithDetails("request-mirror", zclMeteringRequestMirrorCommand, "", "This command is used to request the ESI to mirror Metering Device data ...", NULL),
  emberCommandEntryActionWithDetails("sch-snapshot-resp", zclMeteringSchSnapshotRespCommand, "wv*", "This command is generated in response to a ScheduleSnapshot command, a ...", zclMeteringSchSnapshotRespCommandArguments),
  emberCommandEntryActionWithDetails("start-samp-rsp", zclMeteringStartSampRspCommand, "v", "This command is transmitted by a Metering Device in response to a Star ...", zclMeteringStartSampRspCommandArguments),
  emberCommandEntryActionWithDetails("sup-stat-rsp", zclMeteringSupStatRspCommand, "wwwu", "This command is transmitted by a Metering Device in response to a Chan ...", zclMeteringSupStatRspCommandArguments),
  emberCommandEntryActionWithDetails("take-snapshot-resp", zclMeteringTakeSnapshotRespCommand, "wu", "This command is generated in response to a TakeSnapshot command, and i ...", zclMeteringTakeSnapshotRespCommandArguments),
  emberCommandEntryTerminator(),
};
void zclMfgCodeCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMfgCodeCommandArguments[] = {
  "Manufacturer Specific Id",
  NULL
};
#endif


static void zclMsgCancelCommand(void) {
  zclSimpleServerCommand( ZCL_MESSAGING_CLUSTER_ID,
                          ZCL_CANCEL_MESSAGE_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMsgCancelCommandArguments[] = {
  "message id",
  "message control",
  NULL
};
#endif


static void zclMsgDispCommand(void) {
  zclSimpleServerCommand( ZCL_MESSAGING_CLUSTER_ID,
                          ZCL_DISPLAY_MESSAGE_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMsgDispCommandArguments[] = {
  "message id",
  "message control",
  "start time",
  "duration in minutes",
  "message",
  "optional extended message control",
  NULL
};
#endif


static void zclMsgDispProtdCommand(void) {
  zclSimpleServerCommand( ZCL_MESSAGING_CLUSTER_ID,
                          ZCL_DISPLAY_PROTECTED_MESSAGE_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMsgDispProtdCommandArguments[] = {
  "message id",
  "message control",
  "start time",
  "duration in minutes",
  "message",
  "optional extended message control",
  NULL
};
#endif


static void zclMsgXAllCommand(void) {
  zclSimpleServerCommand( ZCL_MESSAGING_CLUSTER_ID,
                          ZCL_CANCEL_ALL_MESSAGES_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMsgXAllCommandArguments[] = {
  "implementation date time",
  NULL
};
#endif


static EmberCommandEntry emberCommandZclMsgTable[] = {
  emberCommandEntryActionWithDetails("cancel", zclMsgCancelCommand, "wu", "The CancelMessage command provides the ability to cancel the sending o ...", zclMsgCancelCommandArguments),
  emberCommandEntryActionWithDetails("disp", zclMsgDispCommand, "wuwvbu", "Command description for DisplayMessage", zclMsgDispCommandArguments),
  emberCommandEntryActionWithDetails("disp-protd", zclMsgDispProtdCommand, "wuwvbu", "The DisplayProtected Message command is for use with messages that are ...", zclMsgDispProtdCommandArguments),
  emberCommandEntryActionWithDetails("x-all", zclMsgXAllCommand, "w", "The CancelAllMessages command indicates to a client device that it sho ...", zclMsgXAllCommandArguments),
  emberCommandEntryTerminator(),
};
static void zclPrepaymentChgPmtModeRespCommand(void) {
  zclSimpleServerCommand( ZCL_PREPAYMENT_CLUSTER_ID,
                          ZCL_CHANGE_PAYMENT_MODE_RESPONSE_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclPrepaymentChgPmtModeRespCommandArguments[] = {
  "friendly credit",
  "friendly credit calendar id",
  "emergency credit limit",
  "emergency credit threshold",
  NULL
};
#endif


static void zclPrepaymentConsTopUpRespCommand(void) {
  zclSimpleServerCommand( ZCL_PREPAYMENT_CLUSTER_ID,
                          ZCL_CONSUMER_TOP_UP_RESPONSE_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclPrepaymentConsTopUpRespCommandArguments[] = {
  "result type",
  "top up value",
  "source of top up",
  "credit remaining",
  NULL
};
#endif


static void zclPrepaymentPubDebtLogCommand(void) {
  zclSimpleServerCommand( ZCL_PREPAYMENT_CLUSTER_ID,
                          ZCL_PUBLISH_DEBT_LOG_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclPrepaymentPubDebtLogCommandArguments[] = {
  "command index",
  "total number of commands",
  "debt payload",
  "",
  NULL
};
#endif


static void zclPrepaymentPubPrepSsCommand(void) {
  zclSimpleServerCommand( ZCL_PREPAYMENT_CLUSTER_ID,
                          ZCL_PUBLISH_PREPAY_SNAPSHOT_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclPrepaymentPubPrepSsCommandArguments[] = {
  "snapshot id",
  "snapshot time",
  "total snapshots found",
  "command index",
  "total number of commands",
  "snapshot cause",
  "snapshot payload type",
  "snapshot payload",
  "",
  NULL
};
#endif


static void zclPrepaymentPubTopUpLogCommand(void) {
  zclSimpleServerCommand( ZCL_PREPAYMENT_CLUSTER_ID,
                          ZCL_PUBLISH_TOP_UP_LOG_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclPrepaymentPubTopUpLogCommandArguments[] = {
  "command index",
  "total number of commands",
  "top up payload",
  "",
  NULL
};
#endif


static EmberCommandEntry emberCommandZclPrepaymentTable[] = {
  emberCommandEntryActionWithDetails("chg-pmt-mode-resp", zclPrepaymentChgPmtModeRespCommand, "uwww", "This command is send in response to the ChangePaymentMode Command.", zclPrepaymentChgPmtModeRespCommandArguments),
  emberCommandEntryActionWithDetails("cons-top-up-resp", zclPrepaymentConsTopUpRespCommand, "uwuw", "This command is send in response to the ConsumerTopUp Command.", zclPrepaymentConsTopUpRespCommandArguments),
  emberCommandEntryActionWithDetails("pub-debt-log", zclPrepaymentPubDebtLogCommand, "uub*", "This command is used to send the contents of the Repayment Log.", zclPrepaymentPubDebtLogCommandArguments),
  emberCommandEntryActionWithDetails("pub-prep-ss", zclPrepaymentPubPrepSsCommand, "wwuuuwuu*", "This command is generated in response to a GetPrepaySnapshot comman ...", zclPrepaymentPubPrepSsCommandArguments),
  emberCommandEntryActionWithDetails("pub-top-up-log", zclPrepaymentPubTopUpLogCommand, "uub*", "This command is used to send the Top Up Code Log entries to the client ...", zclPrepaymentPubTopUpLogCommandArguments),
  emberCommandEntryTerminator(),
};
static void zclPriceCancelTariffCommand(void) {
  zclSimpleServerCommand( ZCL_PRICE_CLUSTER_ID,
                          ZCL_CANCEL_TARIFF_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclPriceCancelTariffCommandArguments[] = {
  "provider id",
  "issuer tariff id",
  "tariff type",
  NULL
};
#endif


static void zclPricePubBillingPeriodCommand(void) {
  zclSimpleServerCommand( ZCL_PRICE_CLUSTER_ID,
                          ZCL_PUBLISH_BILLING_PERIOD_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclPricePubBillingPeriodCommandArguments[] = {
  "provider id",
  "issuer event id",
  "billing period start time",
  "billing period duration",
  "billing period duration type",
  "tariff type",
  NULL
};
#endif


static void zclPricePubBlockPeriodCommand(void) {
  zclSimpleServerCommand( ZCL_PRICE_CLUSTER_ID,
                          ZCL_PUBLISH_BLOCK_PERIOD_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclPricePubBlockPeriodCommandArguments[] = {
  "provider id",
  "issuer event id",
  "block period start time",
  "block period duration",
  "number of price tiers and number of block thresholds",
  "block period control",
  "block period duration type",
  "tariff type",
  "tariff resolution period",
  NULL
};
#endif


static void zclPricePubBlockThresholdCommand(void) {
  zclSimpleServerCommand( ZCL_PRICE_CLUSTER_ID,
                          ZCL_PUBLISH_BLOCK_THRESHOLDS_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclPricePubBlockThresholdCommandArguments[] = {
  "provider id",
  "issuer event id",
  "start time",
  "issuer tariff id",
  "command index",
  "number of commands",
  "sub payload control",
  "payload",
  "",
  NULL
};
#endif


static void zclPricePubCalValCommand(void) {
  zclSimpleServerCommand( ZCL_PRICE_CLUSTER_ID,
                          ZCL_PUBLISH_CALORIFIC_VALUE_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclPricePubCalValCommandArguments[] = {
  "issuer event id",
  "start time",
  "calorific value",
  "calorific value unit",
  "calorific value trailing digit",
  NULL
};
#endif


static void zclPricePubCo2ValCommand(void) {
  zclSimpleServerCommand( ZCL_PRICE_CLUSTER_ID,
                          ZCL_PUBLISH_C_O2_VALUE_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclPricePubCo2ValCommandArguments[] = {
  "provider id",
  "issuer event id",
  "start time",
  "tariff type",
  "c o2 value",
  "c o2 value unit",
  "c o2 value trailing digit",
  NULL
};
#endif


static void zclPricePubConsolidatedBillCommand(void) {
  zclSimpleServerCommand( ZCL_PRICE_CLUSTER_ID,
                          ZCL_PUBLISH_CONSOLIDATED_BILL_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclPricePubConsolidatedBillCommandArguments[] = {
  "provider id",
  "issuer event id",
  "billing period start time",
  "billing period duration",
  "billing period duration type",
  "tariff type",
  "consolidated bill",
  "currency",
  "bill trailing digit",
  NULL
};
#endif


static void zclPricePubCppEventCommand(void) {
  zclSimpleServerCommand( ZCL_PRICE_CLUSTER_ID,
                          ZCL_PUBLISH_CPP_EVENT_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclPricePubCppEventCommandArguments[] = {
  "provider id",
  "issuer event id",
  "start time",
  "duration in minutes",
  "tariff type",
  "cpp price tier",
  "cpp auth",
  NULL
};
#endif


static void zclPricePubCreditPaymentCommand(void) {
  zclSimpleServerCommand( ZCL_PRICE_CLUSTER_ID,
                          ZCL_PUBLISH_CREDIT_PAYMENT_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclPricePubCreditPaymentCommandArguments[] = {
  "provider id",
  "issuer event id",
  "credit payment due date",
  "credit payment over due amount",
  "credit payment status",
  "credit payment",
  "credit payment date",
  "credit payment ref",
  NULL
};
#endif


static void zclPricePubCurrencyConversionCommand(void) {
  zclSimpleServerCommand( ZCL_PRICE_CLUSTER_ID,
                          ZCL_PUBLISH_CURRENCY_CONVERSION_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclPricePubCurrencyConversionCommandArguments[] = {
  "provider id",
  "issuer event id",
  "start time",
  "old currency",
  "new currency",
  "conversion factor",
  "conversion factor trailing digit",
  "currency change control flags",
  NULL
};
#endif


static void zclPricePubPriceCommand(void) {
  zclSimpleServerCommand( ZCL_PRICE_CLUSTER_ID,
                          ZCL_PUBLISH_PRICE_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclPricePubPriceCommandArguments[] = {
  "provider id",
  "rate label",
  "issuer event id",
  "current time",
  "unit of measure",
  "currency",
  "price trailing digit and price tier",
  "number of price tiers and register tier",
  "start time",
  "duration in minutes",
  "price",
  "price ratio",
  "generation price",
  "generation price ratio",
  "alternate cost delivered",
  "alternate cost unit",
  "alternate cost trailing digit",
  "number of block thresholds",
  "price control",
  "number of generation tiers",
  "generation tier",
  "extended number of price tiers",
  "extended price tier",
  "extended register tier",
  NULL
};
#endif


static void zclPricePubPriceMatrixCommand(void) {
  zclSimpleServerCommand( ZCL_PRICE_CLUSTER_ID,
                          ZCL_PUBLISH_PRICE_MATRIX_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclPricePubPriceMatrixCommandArguments[] = {
  "provider id",
  "issuer event id",
  "start time",
  "issuer tariff id",
  "command index",
  "number of commands",
  "sub payload control",
  "payload",
  "",
  NULL
};
#endif


static void zclPricePubTariffInfoCommand(void) {
  zclSimpleServerCommand( ZCL_PRICE_CLUSTER_ID,
                          ZCL_PUBLISH_TARIFF_INFORMATION_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclPricePubTariffInfoCommandArguments[] = {
  "provider id",
  "issuer event id",
  "issuer tariff id",
  "start time",
  "tariff type charging scheme",
  "tariff label",
  "number of price tiers in use",
  "number of block thresholds in use",
  "unit of measure",
  "currency",
  "price trailing digit",
  "standing charge",
  "tier block mode",
  "block threshold multiplier",
  "block threshold divisor",
  NULL
};
#endif


static void zclPricePubTierLabelsCommand(void) {
  zclSimpleServerCommand( ZCL_PRICE_CLUSTER_ID,
                          ZCL_PUBLISH_TIER_LABELS_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclPricePubTierLabelsCommandArguments[] = {
  "provider id",
  "issuer event id",
  "issuer tariff id",
  "command index",
  "number of commands",
  "number of labels",
  "tier labels payload",
  "",
  NULL
};
#endif


static void zclPricePubXFactorCommand(void) {
  zclSimpleServerCommand( ZCL_PRICE_CLUSTER_ID,
                          ZCL_PUBLISH_CONVERSION_FACTOR_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclPricePubXFactorCommandArguments[] = {
  "issuer event id",
  "start time",
  "conversion factor",
  "conversion factor trailing digit",
  NULL
};
#endif


static EmberCommandEntry emberCommandZclPriceTable[] = {
  emberCommandEntryActionWithDetails("cancel-tariff", zclPriceCancelTariffCommand, "wwu", "The CancelTariff command indicates that all data associated with a par ...", zclPriceCancelTariffCommandArguments),
  emberCommandEntryActionWithDetails("pub-billing-period", zclPricePubBillingPeriodCommand, "wwwbuu", "The PublishBillingPeriod command is generated in response to receiving ...", zclPricePubBillingPeriodCommandArguments),
  emberCommandEntryActionWithDetails("pub-block-period", zclPricePubBlockPeriodCommand, "www0uuuuu", "The PublishBlockPeriod command is generated in response to receiving a ...", zclPricePubBlockPeriodCommandArguments),
  emberCommandEntryActionWithDetails("pub-block-threshold", zclPricePubBlockThresholdCommand, "wwwwuuub*", "The PublishBlockThreshold command is sent in response to a GetBlockThr ...", zclPricePubBlockThresholdCommandArguments),
  emberCommandEntryActionWithDetails("pub-cal-val", zclPricePubCalValCommand, "wwwuu", "The PublishCalorificValue command is sent in response to a GetCalorifi ...", zclPricePubCalValCommandArguments),
  emberCommandEntryActionWithDetails("pub-co2-val", zclPricePubCo2ValCommand, "wwwuwuu", "The PublishCO2Value command is sent in response to a GetCO2Value comma ...", zclPricePubCo2ValCommandArguments),
  emberCommandEntryActionWithDetails("pub-consolidated-bill", zclPricePubConsolidatedBillCommand, "wwwbuuwvu", "The PublishConsolidatedBill command is used to make consolidated billi ...", zclPricePubConsolidatedBillCommandArguments),
  emberCommandEntryActionWithDetails("pub-cpp-event", zclPricePubCppEventCommand, "wwwvuuu", "The PublishCPPEvent command is sent from an ESI to its price clients t ...", zclPricePubCppEventCommandArguments),
  emberCommandEntryActionWithDetails("pub-credit-payment", zclPricePubCreditPaymentCommand, "wwwwuwwb", "The PublishCreditPayment command is used to update the credit payment  ...", zclPricePubCreditPaymentCommandArguments),
  emberCommandEntryActionWithDetails("pub-currency-conversion", zclPricePubCurrencyConversionCommand, "wwwvvwuw", "The PublishCurrencyConversion command is sent in response to a GetCurr ...", zclPricePubCurrencyConversionCommandArguments),
  emberCommandEntryActionWithDetails("pub-price", zclPricePubPriceCommand, "wbwwuvuuwvwuwuwuuuuuuuuu", "The PublishPrice command is generated in response to receiving a Get C ...", zclPricePubPriceCommandArguments),
  emberCommandEntryActionWithDetails("pub-price-matrix", zclPricePubPriceMatrixCommand, "wwwwuuub*", "PublishPriceMatrix command is used to publish the Block Price Informat ...", zclPricePubPriceMatrixCommandArguments),
  emberCommandEntryActionWithDetails("pub-tariff-info", zclPricePubTariffInfoCommand, "wwwwubuuuvuwu00", "The PublishTariffInformation command is sent in response to a GetTarif ...", zclPricePubTariffInfoCommandArguments),
  emberCommandEntryActionWithDetails("pub-tier-labels", zclPricePubTierLabelsCommand, "wwwuuuu*", "The PublishTierLabels command is generated in response to receiving a  ...", zclPricePubTierLabelsCommandArguments),
  emberCommandEntryActionWithDetails("pub-x-factor", zclPricePubXFactorCommand, "wwwu", "The PublishConversionFactor command is sent in response to a GetConver ...", zclPricePubXFactorCommandArguments),
  emberCommandEntryTerminator(),
};
void zclTestResponseOffCommand(void);
void zclTestResponseOnCommand(void);
static EmberCommandEntry emberCommandZclTestResponseTable[] = {
  emberCommandEntryActionWithDetails("off", zclTestResponseOffCommand, "", "Sets a flag so that the application framework WILL NOT respond to the  ...", NULL),
  emberCommandEntryActionWithDetails("on", zclTestResponseOnCommand, "", "Sets a flag so that the application framework WILL respond to the next ...", NULL),
  emberCommandEntryTerminator(),
};
static EmberCommandEntry emberCommandZclTestTable[] = {
  emberCommandEntrySubMenu("response", emberCommandZclTestResponseTable, ""),
  emberCommandEntryTerminator(),
};
void zclTimeCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclTimeCommandArguments[] = {
  "ZigBee UTC time, number of seconds since the year 2000",
  NULL
};
#endif


static void zclTunnelingCloseCommand(void) {
  zclSimpleClientCommand( ZCL_TUNNELING_CLUSTER_ID,
                          ZCL_CLOSE_TUNNEL_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclTunnelingCloseCommandArguments[] = {
  "tunnel id",
  NULL
};
#endif


void zclTunnelingRandomToClientCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclTunnelingRandomToClientCommandArguments[] = {
  "The two byte tunnel id",
  "the length of random data to send to the client",
  NULL
};
#endif


void zclTunnelingRandomToServerCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclTunnelingRandomToServerCommandArguments[] = {
  "The two byte tunnel id",
  "The two byte length of the random data to send",
  NULL
};
#endif


static void zclTunnelingRequestCommand(void) {
  zclSimpleClientCommand( ZCL_TUNNELING_CLUSTER_ID,
                          ZCL_REQUEST_TUNNEL_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclTunnelingRequestCommandArguments[] = {
  "protocol id",
  "manufacturer code",
  "flow control support",
  "maximum incoming transfer size",
  NULL
};
#endif


void zclTunnelingTransferToClientCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclTunnelingTransferToClientCommandArguments[] = {
  "The two byte tunnel id",
  "data to transfer to the client",
  NULL
};
#endif


void zclTunnelingTransferToServerCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclTunnelingTransferToServerCommandArguments[] = {
  "The two byte tunnel id",
  "data to transfer to the client",
  NULL
};
#endif


static EmberCommandEntry emberCommandZclTunnelingTable[] = {
  emberCommandEntryActionWithDetails("close", zclTunnelingCloseCommand, "v", "Client command used to close the tunnel with the serve ...", zclTunnelingCloseCommandArguments),
  emberCommandEntryActionWithDetails("random-to-client", zclTunnelingRandomToClientCommand, "vv", "Send a random amount of data through a tunnel to the server (used for  ...", zclTunnelingRandomToClientCommandArguments),
  emberCommandEntryActionWithDetails("random-to-server", zclTunnelingRandomToServerCommand, "vv", "Send a random amount of data through a tunnel to the server (used for  ...", zclTunnelingRandomToServerCommandArguments),
  emberCommandEntryActionWithDetails("request", zclTunnelingRequestCommand, "uvuv", "RequestTunnel is the client command used to setup a tunnel association ...", zclTunnelingRequestCommandArguments),
  emberCommandEntryActionWithDetails("transfer-to-client", zclTunnelingTransferToClientCommand, "vb", "Transfer data through a tunnel to the client (used for testing)", zclTunnelingTransferToClientCommandArguments),
  emberCommandEntryActionWithDetails("transfer-to-server", zclTunnelingTransferToServerCommand, "vb", "Transfer data through a tunnel to the server.", zclTunnelingTransferToServerCommandArguments),
  emberCommandEntryTerminator(),
};
void zclUseNextSequenceCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclUseNextSequenceCommandArguments[] = {
  "bool value indicating whether raw command will use the incremented seq ...",
  NULL
};
#endif


void zclXDefaultRespCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclXDefaultRespCommandArguments[] = {
  "bool value indicating whether the disable default response bit is set( ...",
  NULL
};
#endif


static EmberCommandEntry emberCommandZclTable[] = {
  emberCommandEntrySubMenu("basic", emberCommandZclBasicTable, ""),
  emberCommandEntrySubMenu("dm", emberCommandZclDmTable, ""),
  emberCommandEntrySubMenu("drlc", emberCommandZclDrlcTable, ""),
  emberCommandEntrySubMenu("global", emberCommandZclGlobalTable, ""),
  emberCommandEntrySubMenu("metering", emberCommandZclMeteringTable, ""),
  emberCommandEntryActionWithDetails("mfg-code", zclMfgCodeCommand, "v", "Sets the two byte manufacturer specific identifier to use for the next ...", zclMfgCodeCommandArguments),
  emberCommandEntrySubMenu("msg", emberCommandZclMsgTable, ""),
  emberCommandEntrySubMenu("prepayment", emberCommandZclPrepaymentTable, ""),
  emberCommandEntrySubMenu("price", emberCommandZclPriceTable, ""),
  emberCommandEntrySubMenu("test", emberCommandZclTestTable, ""),
  emberCommandEntryActionWithDetails("time", zclTimeCommand, "w", "Cli command to call emberAfSetTime function documented in af.h", zclTimeCommandArguments),
  emberCommandEntrySubMenu("tunneling", emberCommandZclTunnelingTable, ""),
  emberCommandEntryActionWithDetails("use-next-sequence", zclUseNextSequenceCommand, "u", "Sets the flag to use the incremented sequence number from the framewor ...", zclUseNextSequenceCommandArguments),
  emberCommandEntryActionWithDetails("x-default-resp", zclXDefaultRespCommand, "u", "Sets the Disable Default Response Frame Control bit to use for the nex ...", zclXDefaultRespCommandArguments),
  emberCommandEntryTerminator(),
};
void zdoActiveEpCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoActiveCommandArguments[] = {
  "Two byte short id, destination for the active endpoint request",
  NULL
};
#endif


void zdoBindCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoBindCommandArguments[] = {
  "Two byte destination node id",
  "Remote device's source endpoint to bind",
  "Remote endpoint to bind",
  "Cluster on which to bind",
  "Remote node EUI64",
  "Binding's dest EUI64.  Usually the local node's EUI64",
  NULL
};
#endif


void zdoIeeeAddressRequestCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoIeeeCommandArguments[] = {
  "Short address of the device for which a long address is requested",
  NULL
};
#endif


void zdoAddClusterCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoInClListAddCommandArguments[] = {
  "Server cluster id",
  NULL
};
#endif


void zdoClearClusterCommand(void);
static EmberCommandEntry emberCommandZdoInClListTable[] = {
  emberCommandEntryActionWithDetails("add", zdoAddClusterCommand, "v", "Add clusters to the known server (in) clusters on this device.", zdoInClListAddCommandArguments),
  emberCommandEntryActionWithDetails("clear", zdoClearClusterCommand, "", "Clear the ZDO list of server (in) clusters.", NULL),
  emberCommandEntryTerminator(),
};
void zdoLeaveRequestCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoLeaveCommandArguments[] = {
  "Target node ID",
  "Remove children",
  "Rejoin after leave",
  NULL
};
#endif


void zdoMatchCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoMatchCommandArguments[] = {
  "Two byte node id indicating wher",
  "Two byte profile id for the match descriptor request",
  NULL
};
#endif


void zdoMgmtBindCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoMgmtBindCommandArguments[] = {
  "Target node ID",
  "Starting index into table query",
  NULL
};
#endif


void zdoMgmtLqiCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoMgmtLqiCommandArguments[] = {
  "Target node ID",
  "Starting index into table query",
  NULL
};
#endif


void zdoNodeCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoNodeCommandArguments[] = {
  "Two byte address for the target device.",
  NULL
};
#endif


void zdoNwkAddressRequestCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoNwkCommandArguments[] = {
  "IEEE address for which a short address is being requested",
  NULL
};
#endif


void zdoNetworkUpdateChannelCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoNwkUpdChanCommandArguments[] = {
  "One byte channel to change to.",
  NULL
};
#endif


void zdoNetworkUpdateChannelCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoNwkUpdChanPgCommandArguments[] = {
  "One byte channel to change to.",
  "One byte page to change to.",
  NULL
};
#endif


void zdoNetworkUpdateScanCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoNwkUpdScanCommandArguments[] = {
  "Two byte short id of the target device",
  "One byte scan duration. Must be in range 0 - 5",
  "Number of scans to perform. Must be in range 1 - 8",
  NULL
};
#endif


void zdoNetworkUpdateScanCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoNwkUpdScanChanMaskCommandArguments[] = {
  "Two byte short id of the target device",
  "One byte scan duration. Must be in range 0 - 5",
  "Number of scans to perform. Must be in range 1 - 8",
  "Four byte channel mask",
  NULL
};
#endif


void zdoNetworkUpdateSetCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoNwkUpdSetCommandArguments[] = {
  "Two byte network manager id",
  "Four byte channel mask",
  NULL
};
#endif


static EmberCommandEntry emberCommandZdoNwkUpdTable[] = {
  emberCommandEntryActionWithDetails("chan", zdoNetworkUpdateChannelCommand, "u", "Sends an update channel request.", zdoNwkUpdChanCommandArguments),
  emberCommandEntryActionWithDetails("chanPg", zdoNetworkUpdateChannelCommand, "uu", "Sends an update channel page reques ...", zdoNwkUpdChanPgCommandArguments),
  emberCommandEntryActionWithDetails("scan", zdoNetworkUpdateScanCommand, "vuv", "Performs an energy scan.", zdoNwkUpdScanCommandArguments),
  emberCommandEntryActionWithDetails("scan-chan-mask", zdoNetworkUpdateScanCommand, "vuvw", "Performs an energy scan on given channel mas ...", zdoNwkUpdScanChanMaskCommandArguments),
  emberCommandEntryActionWithDetails("set", zdoNetworkUpdateSetCommand, "vw", "Broadcasts the ID of the new network manager and active channels.", zdoNwkUpdSetCommandArguments),
  emberCommandEntryTerminator(),
};
void zdoAddClusterCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoOutClListAddCommandArguments[] = {
  "Client cluster ids",
  NULL
};
#endif


void zdoClearClusterCommand(void);
static EmberCommandEntry emberCommandZdoOutClListTable[] = {
  emberCommandEntryActionWithDetails("add", zdoAddClusterCommand, "v", "Add clusters to the known client (out) clusters on this device.", zdoOutClListAddCommandArguments),
  emberCommandEntryActionWithDetails("clear", zdoClearClusterCommand, "", "Clear the ZDO list of client (out) clusters.", NULL),
  emberCommandEntryTerminator(),
};
void zdoPowerDescriptorRequestCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoPowerCommandArguments[] = {
  "Target node ID",
  NULL
};
#endif


void zdoRouteRequestCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoRouteCommandArguments[] = {
  "Target node ID",
  "The index of the remote node's routing table to request.",
  NULL
};
#endif


void zdoSimpleCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoSimpleCommandArguments[] = {
  "Short address of the device where the simple descriptor request should ...",
  "The endpoint on the target device where the simple descriptor request  ...",
  NULL
};
#endif


void zdoUnbindGroupCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoUnbindGroupCommandArguments[] = {
  "Target node ID",
  "The source EUI64 of the binding (the remote device's EUI64)",
  "The source endpoint of the binding.",
  "The cluster ID to unbind.",
  "The group address in the binding",
  NULL
};
#endif


void zdoUnbindUnicastCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoUnbindUnicastCommandArguments[] = {
  "Target node ID",
  "The source EUI64 of the binding (the remote device's EUI64)",
  "The source endpoint of the binding.",
  "The cluster ID to unbind.",
  "The destination EUI64 in the binding (usually the local node's EUI64",
  "The destination endpoint of the binding",
  NULL
};
#endif


static EmberCommandEntry emberCommandZdoUnbindTable[] = {
  emberCommandEntryActionWithDetails("group", zdoUnbindGroupCommand, "vbuvv", "Sends an unbind request for a multicast binding to the target device.", zdoUnbindGroupCommandArguments),
  emberCommandEntryActionWithDetails("unicast", zdoUnbindUnicastCommand, "vbuvbu", "Sends an unbind request for a unicast binding to the target device.", zdoUnbindUnicastCommandArguments),
  emberCommandEntryTerminator(),
};
static EmberCommandEntry emberCommandZdoTable[] = {
  emberCommandEntryActionWithDetails("active", zdoActiveEpCommand, "v", "Send an active endpoint request to the device with the given short id.", zdoActiveCommandArguments),
  emberCommandEntryActionWithDetails("bind", zdoBindCommand, "vuuvbb", "Send a ZDO Bind command to a device specified in the command arguments ...", zdoBindCommandArguments),
  emberCommandEntryActionWithDetails("ieee", zdoIeeeAddressRequestCommand, "v", "Request an ieee address based on a given node id.", zdoIeeeCommandArguments),
  emberCommandEntrySubMenu("in-cl-list", emberCommandZdoInClListTable, ""),
  emberCommandEntryActionWithDetails("leave", zdoLeaveRequestCommand, "vuu", "Send a ZDO Management Leave command to the target device.", zdoLeaveCommandArguments),
  emberCommandEntryActionWithDetails("match", zdoMatchCommand, "vv", "Sends a matchDescriptorsRequest to the given destination with the give ...", zdoMatchCommandArguments),
  emberCommandEntryActionWithDetails("mgmt-bind", zdoMgmtBindCommand, "vu", "Send a ZDO MGMT-Bind (Binding Table) Request to the target device.", zdoMgmtBindCommandArguments),
  emberCommandEntryActionWithDetails("mgmt-lqi", zdoMgmtLqiCommand, "vu", "Send a ZDO MGMT-LQI (LQI Table) Request to the target device.", zdoMgmtLqiCommandArguments),
  emberCommandEntryActionWithDetails("node", zdoNodeCommand, "v", "Sends a node descriptor request to a given target device", zdoNodeCommandArguments),
  emberCommandEntryActionWithDetails("nwk", zdoNwkAddressRequestCommand, "b", "Sends a network address request for the given IEEE address.", zdoNwkCommandArguments),
  emberCommandEntrySubMenu("nwk-upd", emberCommandZdoNwkUpdTable, ""),
  emberCommandEntrySubMenu("out-cl-list", emberCommandZdoOutClListTable, ""),
  emberCommandEntryActionWithDetails("power", zdoPowerDescriptorRequestCommand, "v", "Send a ZDO Power Descriptor Request to the target device.", zdoPowerCommandArguments),
  emberCommandEntryActionWithDetails("route", zdoRouteRequestCommand, "vu", "Send a ZDO route request command to the target.", zdoRouteCommandArguments),
  emberCommandEntryActionWithDetails("simple", zdoSimpleCommand, "vu", "Sends out a simple descriptor request for the short address and endpoi ...", zdoSimpleCommandArguments),
  emberCommandEntrySubMenu("unbind", emberCommandZdoUnbindTable, ""),
  emberCommandEntryTerminator(),
};
EmberCommandEntry emberCommandTable[] = {
  emberCommandEntryActionWithDetails("bsend", emAfCliBsendCommand, "u", "Send using a binding based on the clusterId in the globalApsFrame and  ...", bsendCommandArguments),
  emberCommandEntrySubMenu("changekey", emberCommandChangekeyTable, ""),
  emberCommandEntrySubMenu("debugprint", emberCommandDebugprintTable, ""),
  emberCommandEntryActionWithDetails("echo", echoCommand, "u", "Turns echo on the command line on or off depending on the argument", echoCommandArguments),
  emberCommandEntrySubMenu("endpoint", emberCommandEndpointTable, ""),
  emberCommandEntryActionWithDetails("events", printEvents, "", "Print the list of timer events.", NULL),
  emberCommandEntryActionWithDetails("help", helpCommand, "", "Prints out the cli command options for the device", NULL),
  emberCommandEntryActionWithDetails("info", emAfCliInfoCommand, "", "Gives information about the local node", NULL),
  emberCommandEntrySubMenu("interpan", emberCommandInterpanTable, ""),
  emberCommandEntrySubMenu("keys", emberCommandKeysTable, ""),
  emberCommandEntryActionWithDetails("libs", printAllLibraryStatus, "", "Lists which optional libraries of the stack are implemented on this de ...", NULL),
  emberCommandEntrySubMenu("network", emberCommandNetworkTable, ""),
  emberCommandEntrySubMenu("option", emberCommandOptionTable, ""),
  emberCommandEntrySubMenu("plugin", emberCommandPluginTable, ""),
  emberCommandEntrySubMenu("print", emberCommandPrintTable, ""),
  emberCommandEntryActionWithDetails("raw", emAfCliRawCommand, "vb", "Creates a message by specifying the raw byte ...", rawCommandArguments),
  emberCommandEntryActionWithDetails("read", emAfCliReadCommand, "uvvu", "Read an attribute from the local attribute tabl ...", readCommandArguments),
  emberCommandEntryActionWithDetails("reset", resetCommand, "", "resets the device", NULL),
  emberCommandEntrySubMenu("security", emberCommandSecurityTable, ""),
  emberCommandEntryActionWithDetails("send", emAfCliSendCommand, "vuu", "Send a pre-buffered message from a given endpoint to an endpoint on a  ...", sendCommandArguments),
  emberCommandEntryActionWithDetails("send-using-multicast-binding", emAfCliSendUsingMulticastBindingCommand, "u", "When sending using a binding, specify whether a multicast binding shou ...", sendUsingMulticastBindingCommandArguments),
  emberCommandEntryActionWithDetails("send_multicast", emAfCliSendCommand, "vu", "Send a pre-buffered multicast message to a given group id from a given ...", sendMulticastCommandArguments),
  emberCommandEntryActionWithDetails("timesync", emAfCliTimesyncCommand, "vuu", "This sends a read attr for the time of the device specifie ...", timesyncCommandArguments),
  emberCommandEntryActionWithDetails("version", emAfCliVersionCommand, "", "Shows the version of the software", NULL),
  emberCommandEntryActionWithDetails("write", emAfCliWriteCommand, "uvvuub", "Write an attribute value into the local attribute table", writeCommandArguments),
  emberCommandEntrySubMenu("zcl", emberCommandZclTable, ""),
  emberCommandEntrySubMenu("zdo", emberCommandZdoTable, ""),
#ifdef EMBER_AF_ENABLE_CUSTOM_COMMANDS
  CUSTOM_COMMANDS
#endif // EMBER_AF_ENABLE_CUSTOM_COMMANDS
  emberCommandEntryTerminator(),
};
